a_i = [
    [
        0.03674512356519699,
        0.33299553394317627,
        0.0,
    ],
    [
        0.2700100243091583,
        -0.19832001626491547,
        0.0,
    ],
    [
        -0.3067551851272583,
        -0.13467556238174438,
        0.0,
    ],
]
v_i = [
    [
        0.0067016854882240295,
        0.13175232708454132,
        0.0,
    ],
    [
        0.11075000464916229,
        -0.07168000191450119,
        0.0,
    ],
    [
        -0.11745169013738632,
        -0.06007232889533043,
        0.0,
    ],
]
a_j1 = [
    [
        -0.1352253556251526,
        0.23317712545394897,
        0.0,
    ],
    [
        0.26954999566078186,
        0.0005200000014156103,
        0.0,
    ],
    [
        -0.13432464003562927,
        -0.23369716107845306,
        0.0,
    ],
]
a_j2 = [
    [
        -0.3714927136898041,
        0.09778419137001038,
        0.0,
    ],
    [
        0.2704299986362457,
        0.2728300094604492,
        0.0,
    ],
    [
        0.10106276720762253,
        -0.37061426043510437,
        0.0,
    ],
]
v_j = [
    [
        -0.11745171248912811,
        0.06007229909300804,
        0.0,
    ],
    [
        0.11075000464916229,
        0.07168000191450119,
        0.0,
    ],
    [
        0.006701719015836716,
        -0.13175232708454132,
        0.0,
    ],
]
l_j = [
    0.08299999684095383,
    0.08299999684095383,
    0.08299999684095383,
]

[loss_config]
SO2_angle_min = [
    -3.1415927410125732,
    -3.1415927410125732,
    -3.1415927410125732,
]
SO2_angle_max = [
    3.1415927410125732,
    3.1415927410125732,
    3.1415927410125732,
]
barrier_weight = [
    0.0,
    0.0,
    0.0,
]