initial_position = [
    1.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.2750000059604645,
    0.9063077569007874,
    0.4226182699203491,
    0.9063077569007874,
    0.4226182699203491,
    0.9063077569007874,
    0.4226182699203491,
    0.3406500220298767,
    0.3406500220298767,
    0.3406500220298767,
    0.31060001254081726,
    0.31060001254081726,
    0.31060001254081726,
    0.31060001254081726,
    0.31060001254081726,
    0.31060001254081726,
]