[env]
    BINDGEN_EXTRA_CLANG_ARGS = "-I\"C:\\Program Files (x86)\\Windows Kits\\10\\Include\\10.0.26100.0\\ucrt\" -I\"C:\\Program Files (x86)\\Windows Kits\\10\\Include\\10.0.26100.0\\um\" -I\"C:\\Program Files (x86)\\Windows Kits\\10\\Include\\10.0.26100.0\\shared\" -I\"C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.44.35207\\include\""

[target.aarch64-unknown-linux-gnu]
    linker    = "/usr/bin/cc"
    rustflags = ["-Clinker=/usr/bin/cc"]
